print('Welcome to the simple calculator')
print('This calculator can only divide two numbers supplied by the user.')
x= float (input ('Add your first number'))
y= float (input('Add your second number'))
output= (x)/(y)
print(output)